apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocdibm
spec:
  project: default


  source:
    repoURL: https://github.com/Chetancloud/argoCD
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: myappibm


  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
